### ISSUE TITLE
Import statement in NPM Readme is not up to date

### ISSUE THREAD

**Issue by mhelmetag** [akiokio/ReactSignupLoginComponent#1]
Not urgent or anything as it looks like you've updated the readme in `master`, but the one on NPM still reflects an incorrect import statement for your component:
<img width="725" alt="screen shot 2017-03-26 at 4 16 52 pm" src="https://cloud.githubusercontent.com/assets/8609429/24336216/c4d0f256-123f-11e7-8feb-1ba28e32f43f.png">

When you have the chance, could you push the most recent readme changes to NPM to update the one they have?

Thanks a bunch for this component!!!

**Comment by akiokio** [comment]
Nice catch @mhelmetag! Thanks!

I will update soon, I'm preparing an update with some improvements :)

**Comment by akiokio** [comment]
Done 🎉

**Comment by mhelmetag** [comment]
Thanks @akiokio <3
