### ISSUE TITLE
Proptypes Error

### ISSUE THREAD

**Issue by ahsan7786** [akiokio/ReactSignupLoginComponent#27]
Hi,

using this component in my app generate proptypes error. even testing on [https://runkit.com/npm/react-signup-login-component](url) generates same error 
![issue](https://user-images.githubusercontent.com/24411496/36154285-c47609ba-10f2-11e8-8216-a5279e24ca26.PNG)

**Comment by akiokio** [comment]
Hi @ahsan7786, I've just updated the package to the version 1.0.3. It's just a clean up to force npm to update their files. Looks like it's working fine now, can you test it again?

About the Runkit, now it's giving `"Unexpected token import"` which makes sense based on their premise `Try any Node.js package right in your browser`. The es6 syntax (import/export) is not available in node (commonjs). Makes sense?

**Comment by ahsan7786** [comment]
@akiokio  i will check and update you in this regard :)

**Comment by ahsan7786** [comment]
its working fine now @akiokio

**Comment by akiokio** [comment]
great! I'll the issue 👍
