### ISSUE TITLE
customization in form

### ISSUE THREAD

**Issue by ashutoshnjha** [akiokio/ReactSignupLoginComponent#57]
How can I customize the field and buttons?
e,g instead of Username I want to have Email 
Signup => Join us

**Comment by akiokio** [comment]
@ashutoshnjha you can't yet but that a good idea, I'll try to release a new version today where you can provide your own values to the labels

**Comment by akiokio** [comment]
@ashutoshnjha happy to inform that as of `v1.2.0` the package now accepts custom values to all labels 🎉 :
![image](https://user-images.githubusercontent.com/1786578/44561169-29f06f00-a708-11e8-9f5e-92b775ee6d1c.png)

**Comment by ashutoshnjha** [comment]
Thank you Akiokio for the change.
It is working at my end.  I am a new comer to the react world this  change will help us to write any  further customization based on my exploration.
Thanks a lot for a quicker response.
